selector_events.py [LINE:53] #DEBUG    [2022-07-04 02:17:40,321]  Using selector: KqueueSelector
connectionpool.py [LINE:1005] #DEBUG    [2022-07-04 02:17:40,335]  Starting new HTTPS connection (1): ton-blockchain.github.io:443
connectionpool.py [LINE:465] #DEBUG    [2022-07-04 02:17:40,620]  https://ton-blockchain.github.io:443 "GET /global.config.json HTTP/1.1" 200 5150
tonlibjson.py [LINE:192] #DEBUG    [2022-07-04 02:17:40,637]  Pruning 0 tasks
client.py [LINE:91] #INFO     [2022-07-04 02:17:40,656]  TonLib #000 inited successfully
api.py [LINE:133] #DEBUG    [2022-07-04 02:17:40,656]  Make request: "sendMessage" with data: "{'chat_id': 6405640, 'text': 'Script is running!!!!!'}" and files "None"
api.py [LINE:95] #DEBUG    [2022-07-04 02:17:41,004]  Response for sendMessage: [200] "'{"ok":true,"result":{"message_id":24,"from":{"id":5350218964,"is_bot":true,"first_name":"Bot_for_test","username":"Loujessler_bot_for_test_bot"},"chat":{"id":6405640,"first_name":"rmdir","last_name":"life","username":"rmdir_life","type":"private"},"date":1656886661,"text":"Script is running!!!!!"}}'"
tonlibjson.py [LINE:212] #CRITICAL [2022-07-04 02:17:42,857]  Tonlib #000 crashed: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 566, in run_until_complete
    self.run_forever()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 534, in run_forever
    self._run_once()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 1771, in _run_once
    handle._run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/loujessler/Documents/Telegram_bots/tonbrute_force/main.py", line 105, in new_ton_lib
    while len(seed) != 24:
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/loujessler/Documents/code/tonbrute_force/lib/python3.7/site-packages/pytonlib/tonlibjson.py", line 207, in read_results
    result = await asyncio.wait_for(self.loop.run_in_executor(None, receive_func), timeout=timeout + delta)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/tasks.py", line 435, in wait_for
    await waiter
concurrent.futures._base.CancelledError

tonlibjson.py [LINE:237] #CRITICAL [2022-07-04 02:17:42,858]  Task del_expired_futures_loop failed: 
